// <auto-generated />
namespace GoerTekLover.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Add0 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add0));
        
        string IMigrationMetadata.Id
        {
            get { return "201401211405589_Add0"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
